#!/usr/bin/env python3
"""
generate_index.py

Scans a codeforces-kharryhsu repo and builds INDEX.md, a
difficulty-sorted table of every solved problem, pulling rating/tags
from the Codeforces API. Run this from the repo root:

    python generate_index.py

Expected layout (both are optional, script adapts to what exists):

    Contest/
        Codeforces Round 1114 (Div 3)/
            2254A.cpp
            2254B.cpp
    800/
        486A/
            486A.cpp
    900/
        123B.py
    ...

Only source files are picked up: .cpp .cc .c .py .java .kt .rs .go
Binaries (.exe, .out, .o) are ignored.

No file is duplicated: each problem appears once in INDEX.md, with a
relative path pointing at wherever it actually lives on disk.
"""

import json
import os
import re
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
CONTEST_DIR_NAMES = {"contest", "contests"}
SOURCE_EXTS = {".cpp", ".cc", ".c", ".py", ".java", ".kt", ".rs", ".go"}
PROBLEM_RE = re.compile(r"^(\d+)([A-Za-z]\d*)")
CF_API_URL = "https://codeforces.com/api/problemset.problems"


def fetch_problem_metadata():
    """Return {(contestId, index): {"rating": int|None, "tags": [str]}}."""
    print("Fetching problem ratings from Codeforces API...", file=sys.stderr)
    try:
        with urllib.request.urlopen(CF_API_URL, timeout=15) as resp:
            data = json.load(resp)
    except Exception as e:
        print(f"Warning: could not reach Codeforces API ({e}). "
              f"Ratings will be blank.", file=sys.stderr)
        return {}

    if data.get("status") != "OK":
        print("Warning: Codeforces API returned an error.", file=sys.stderr)
        return {}

    meta = {}
    for p in data["result"]["problems"]:
        key = (p["contestId"], p["index"])
        meta[key] = {
            "rating": p.get("rating"),
            "tags": p.get("tags", []),
        }
    return meta


def parse_problem_id(stem):
    """'2254A' -> (2254, 'A'). Returns None if it doesn't match."""
    m = PROBLEM_RE.match(stem)
    if not m:
        return None
    return int(m.group(1)), m.group(2)


def find_contest_label(path):
    """Walk up from a file to find the folder inside Contest/ it belongs to."""
    for parent in path.parents:
        if parent.parent.name.lower() in CONTEST_DIR_NAMES:
            return parent.name
    return None


def scan_repo():
    """Returns list of dicts: contestId, index, path, contest_label."""
    entries = []
    seen = set()

    for path in REPO_ROOT.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix.lower() not in SOURCE_EXTS:
            continue

        parsed = parse_problem_id(path.stem)
        if not parsed:
            continue
        contest_id, index = parsed
        key = (contest_id, index)
        if key in seen:
            continue
        seen.add(key)

        rel_path = path.relative_to(REPO_ROOT)
        contest_label = find_contest_label(path)

        entries.append({
            "contestId": contest_id,
            "index": index,
            "path": str(rel_path).replace(os.sep, "/"),
            "contest_label": contest_label or "practice / upsolved",
        })

    return entries


def build_index_md(entries, meta):
    for e in entries:
        m = meta.get((e["contestId"], e["index"]), {})
        e["rating"] = m.get("rating")
        e["tags"] = ", ".join(m.get("tags", [])[:4])

    # Unrated problems sort last; otherwise ascending by rating.
    entries.sort(key=lambda e: (e["rating"] is None, e["rating"] or 0, e["contestId"]))

    lines = [
        "# Problem Index",
        "",
        "Auto-generated by `generate_index.py`. Do not edit by hand,",
        "",
        "| Problem | Rating | Tags | Contest | Path |",
        "|---|---|---|---|---|",
    ]
    for e in entries:
        problem_id = f"{e['contestId']}{e['index']}"
        rating = e["rating"] if e["rating"] is not None else "?"
        link = f"https://codeforces.com/problemset/problem/{e['contestId']}/{e['index']}"
        lines.append(
            f"| [{problem_id}]({link}) | {rating} | {e['tags']} | "
            f"{e['contest_label']} | `{e['path']}` |"
        )

    total = len(entries)
    rated = sum(1 for e in entries if e["rating"] is not None)
    lines += [
        "",
        f"**Total solved:** {total}  ",
        f"**Rated:** {rated}",
    ]
    return "\n".join(lines) + "\n"


def main():
    entries = scan_repo()
    if not entries:
        print("No solution files found. Run this from the repo root.", file=sys.stderr)
        sys.exit(1)

    meta = fetch_problem_metadata()
    content = build_index_md(entries, meta)

    out_path = REPO_ROOT / "INDEX.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {out_path} ({len(entries)} problems).", file=sys.stderr)


if __name__ == "__main__":
    main()